-- Seed the Dukaan Cunto starter templates (Somali grocery / dukaan cunto).
--
-- Two sibling templates share one global catalog (categories, items,
-- units, aliases):
--   * test_dukaan_cunto  — full: ~77 items + quick actions, for seeded test shops.
--   * empty_dukaan_cunto — config only (settings + expense categories),
--     no inventory / no quick actions, for onboarding a real shop from scratch.
--
-- Mirrors 0016 (grocery). Idempotent: on conflict do nothing. Authoritative
-- apply path is `supabase db reset`; apply_template(shop, template) materializes.

--------------------------------------------------------------------
-- 1. Units not yet in the global unit table (0002).
--------------------------------------------------------------------
insert into public.unit (code, default_label, label_translations, is_active)
values
  ('jerrycan', 'Jerrycan', jsonb_build_object('so', 'Jerigan'), true),
  ('can', 'Can', jsonb_build_object('so', 'Qasacad'), true),
  ('tin', 'Tin', jsonb_build_object('so', 'Tini'), true),
  ('jar', 'Jar', jsonb_build_object('so', 'Jaar'), true)
on conflict (code) do nothing;

--------------------------------------------------------------------
-- 2. Categories (Somali set for dukaan cunto).
--------------------------------------------------------------------
insert into public.category (code, name, name_translations, sort_order)
values
  ('raashin', 'Staples', jsonb_build_object('en', 'Staples', 'so', 'Raashin'), 1),
  ('cabitaan', 'Beverages', jsonb_build_object('en', 'Beverages', 'so', 'Cabitaan'), 2),
  ('macmacaan', 'Snacks', jsonb_build_object('en', 'Snacks', 'so', 'Macmacaan'), 3),
  ('xawaash', 'Spices', jsonb_build_object('en', 'Spices', 'so', 'Xawaash'), 4),
  ('qasacado', 'Canned', jsonb_build_object('en', 'Canned', 'so', 'Qasacado'), 5),
  ('guriga', 'Household', jsonb_build_object('en', 'Household', 'so', 'Guriga'), 6),
  ('caafimaad', 'Health', jsonb_build_object('en', 'Health', 'so', 'Caafimaad'), 7)
on conflict (code) do nothing;

--------------------------------------------------------------------
-- 3. Items (global SKUs, slim — display name lives in item_alias).
--------------------------------------------------------------------
insert into public.item (code, category_id, base_unit_code, is_active)
select i.item_code, c.id, i.base_unit, true
from (values
  ('bariis_basmati_25kg', 'raashin', 'bag'),
  ('bariis_cad_25kg', 'raashin', 'bag'),
  ('bariis_kg', 'raashin', 'kg'),
  ('sonkor_50kg', 'raashin', 'bag'),
  ('sonkor_kg', 'raashin', 'kg'),
  ('daqiiq_50kg', 'raashin', 'bag'),
  ('daqiiq_kg', 'raashin', 'kg'),
  ('bur_caws_kg', 'raashin', 'kg'),
  ('saliid_20l', 'raashin', 'jerrycan'),
  ('saliid_5l', 'raashin', 'jerrycan'),
  ('saliid_1l', 'raashin', 'bottle'),
  ('baasto_500g', 'raashin', 'packet'),
  ('spageti_500g', 'raashin', 'packet'),
  ('macrooni_400g', 'raashin', 'packet'),
  ('digir_kg', 'raashin', 'kg'),
  ('misir_kg', 'raashin', 'kg'),
  ('loobiya_kg', 'raashin', 'kg'),
  ('galley_kg', 'raashin', 'kg'),
  ('cusbo_kg', 'raashin', 'kg'),
  ('timir_500g', 'raashin', 'packet'),
  ('shaah_caleen_250g', 'cabitaan', 'packet'),
  ('shaah_caleen_500g', 'cabitaan', 'packet'),
  ('bun_250g', 'cabitaan', 'packet'),
  ('caano_budo_400g', 'cabitaan', 'tin'),
  ('caano_budo_2500g', 'cabitaan', 'tin'),
  ('caano_fariid_1l', 'cabitaan', 'bottle'),
  ('biyo_500ml', 'cabitaan', 'bottle'),
  ('biyo_1500ml', 'cabitaan', 'bottle'),
  ('biyo_carton', 'cabitaan', 'carton'),
  ('soda_300ml', 'cabitaan', 'bottle'),
  ('soda_1500ml', 'cabitaan', 'bottle'),
  ('casiir_1l', 'cabitaan', 'bottle'),
  ('vimto_1l', 'cabitaan', 'bottle'),
  ('tamar_hindi_1l', 'cabitaan', 'bottle'),
  ('biskut_packet', 'macmacaan', 'packet'),
  ('shukulaato', 'macmacaan', 'piece'),
  ('nacnac', 'macmacaan', 'packet'),
  ('cadar_xabag', 'macmacaan', 'packet'),
  ('shibis', 'macmacaan', 'packet'),
  ('macsaro', 'macmacaan', 'packet'),
  ('kornfaleeks_375g', 'macmacaan', 'box'),
  ('halwa_kg', 'macmacaan', 'piece'),
  ('malab_500g', 'macmacaan', 'jar'),
  ('subag_kg', 'macmacaan', 'tin'),
  ('jam_400g', 'macmacaan', 'jar'),
  ('xawaash_100g', 'xawaash', 'packet'),
  ('basbaas_budo_100g', 'xawaash', 'packet'),
  ('filfil_100g', 'xawaash', 'packet'),
  ('kamuun_100g', 'xawaash', 'packet'),
  ('hayl_50g', 'xawaash', 'packet'),
  ('qorfe_50g', 'xawaash', 'packet'),
  ('huruud_100g', 'xawaash', 'packet'),
  ('maraq_cube', 'xawaash', 'box'),
  ('khal_500ml', 'xawaash', 'bottle'),
  ('tamaate_paste_400g', 'qasacado', 'can'),
  ('tamaate_paste_70g', 'qasacado', 'can'),
  ('tuun_qasacad', 'qasacado', 'can'),
  ('sardiin_qasacad', 'qasacado', 'can'),
  ('digir_qasacad', 'qasacado', 'can'),
  ('tamaate_qasacad', 'qasacado', 'can'),
  ('caano_qasacad', 'qasacado', 'can'),
  ('saabuun_dharka', 'guriga', 'piece'),
  ('daacuun_1kg', 'guriga', 'packet'),
  ('saabuun_gacmeed', 'guriga', 'piece'),
  ('shaambo_400ml', 'guriga', 'bottle'),
  ('cadayga', 'guriga', 'piece'),
  ('caleen_suuf', 'guriga', 'piece'),
  ('kabriid', 'guriga', 'packet'),
  ('shamac', 'guriga', 'piece'),
  ('bataari_aa', 'guriga', 'packet'),
  ('baaldi', 'guriga', 'piece'),
  ('xaaqin', 'guriga', 'piece'),
  ('foyl', 'guriga', 'piece'),
  ('dabqaad', 'guriga', 'piece'),
  ('caafimaad_panadol', 'caafimaad', 'packet'),
  ('caafimaad_plaster', 'caafimaad', 'packet'),
  ('caafimaad_cotton', 'caafimaad', 'packet')
) as i(item_code, category_code, base_unit)
join public.category c on c.code = i.category_code
on conflict (code) do nothing;

--------------------------------------------------------------------
-- 4. Item aliases — display (one per language) + search nicknames.
--------------------------------------------------------------------
insert into public.item_alias (item_id, alias_text, language_code, is_display, source, weight)
select i.id, a.alias_text, a.lang, true, 'platform', 0
from public.item i
join (values
  ('bariis_basmati_25kg', 'so', 'Bariis Basmati 25kg'),
  ('bariis_basmati_25kg', 'en', 'Basmati Rice 25kg'),
  ('bariis_cad_25kg', 'so', 'Bariis Cad 25kg'),
  ('bariis_cad_25kg', 'en', 'White Rice 25kg'),
  ('bariis_kg', 'so', 'Bariis 1kg'),
  ('bariis_kg', 'en', 'Rice 1kg'),
  ('sonkor_50kg', 'so', 'Sonkor 50kg'),
  ('sonkor_50kg', 'en', 'Sugar 50kg'),
  ('sonkor_kg', 'so', 'Sonkor 1kg'),
  ('sonkor_kg', 'en', 'Sugar 1kg'),
  ('daqiiq_50kg', 'so', 'Daqiiq 50kg'),
  ('daqiiq_50kg', 'en', 'Wheat Flour 50kg'),
  ('daqiiq_kg', 'so', 'Daqiiq 1kg'),
  ('daqiiq_kg', 'en', 'Wheat Flour 1kg'),
  ('bur_caws_kg', 'so', 'Bur Caws 1kg'),
  ('bur_caws_kg', 'en', 'Semolina 1kg'),
  ('saliid_20l', 'so', 'Saliid Cunto 20L'),
  ('saliid_20l', 'en', 'Cooking Oil 20L'),
  ('saliid_5l', 'so', 'Saliid Cunto 5L'),
  ('saliid_5l', 'en', 'Cooking Oil 5L'),
  ('saliid_1l', 'so', 'Saliid Cunto 1L'),
  ('saliid_1l', 'en', 'Cooking Oil 1L'),
  ('baasto_500g', 'so', 'Baasto 500g'),
  ('baasto_500g', 'en', 'Pasta 500g'),
  ('spageti_500g', 'so', 'Spageti 500g'),
  ('spageti_500g', 'en', 'Spaghetti 500g'),
  ('macrooni_400g', 'so', 'Macrooni 400g'),
  ('macrooni_400g', 'en', 'Macaroni 400g'),
  ('digir_kg', 'so', 'Digir 1kg'),
  ('digir_kg', 'en', 'Beans 1kg'),
  ('misir_kg', 'so', 'Misir 1kg'),
  ('misir_kg', 'en', 'Lentils 1kg'),
  ('loobiya_kg', 'so', 'Loobiya 1kg'),
  ('loobiya_kg', 'en', 'Cowpeas 1kg'),
  ('galley_kg', 'so', 'Galley 1kg'),
  ('galley_kg', 'en', 'Maize 1kg'),
  ('cusbo_kg', 'so', 'Cusbo 1kg'),
  ('cusbo_kg', 'en', 'Salt 1kg'),
  ('timir_500g', 'so', 'Timir 500g'),
  ('timir_500g', 'en', 'Dates 500g'),
  ('shaah_caleen_250g', 'so', 'Shaah Caleen 250g'),
  ('shaah_caleen_250g', 'en', 'Tea Leaves 250g'),
  ('shaah_caleen_500g', 'so', 'Shaah Caleen 500g'),
  ('shaah_caleen_500g', 'en', 'Tea Leaves 500g'),
  ('bun_250g', 'so', 'Bun 250g'),
  ('bun_250g', 'en', 'Coffee 250g'),
  ('caano_budo_400g', 'so', 'Caano Budo 400g'),
  ('caano_budo_400g', 'en', 'Milk Powder 400g'),
  ('caano_budo_2500g', 'so', 'Caano Budo 2.5kg'),
  ('caano_budo_2500g', 'en', 'Milk Powder 2.5kg'),
  ('caano_fariid_1l', 'so', 'Caano Fariid 1L'),
  ('caano_fariid_1l', 'en', 'Fresh Milk 1L'),
  ('biyo_500ml', 'so', 'Biyo 500ml'),
  ('biyo_500ml', 'en', 'Water 500ml'),
  ('biyo_1500ml', 'so', 'Biyo 1.5L'),
  ('biyo_1500ml', 'en', 'Water 1.5L'),
  ('biyo_carton', 'so', 'Biyo Carton 12x1.5L'),
  ('biyo_carton', 'en', 'Water Carton 12x1.5L'),
  ('soda_300ml', 'so', 'Cabitaan 300ml'),
  ('soda_300ml', 'en', 'Soda 300ml'),
  ('soda_1500ml', 'so', 'Cabitaan 1.5L'),
  ('soda_1500ml', 'en', 'Soda 1.5L'),
  ('casiir_1l', 'so', 'Casiir 1L'),
  ('casiir_1l', 'en', 'Juice 1L'),
  ('vimto_1l', 'so', 'Vimto 1L'),
  ('vimto_1l', 'en', 'Vimto 1L'),
  ('tamar_hindi_1l', 'so', 'Tamar Hindi 1L'),
  ('tamar_hindi_1l', 'en', 'Tamarind Drink 1L'),
  ('biskut_packet', 'so', 'Biskut'),
  ('biskut_packet', 'en', 'Biscuits'),
  ('shukulaato', 'so', 'Shukulaato'),
  ('shukulaato', 'en', 'Chocolate'),
  ('nacnac', 'so', 'Nacnac'),
  ('nacnac', 'en', 'Sweets'),
  ('cadar_xabag', 'so', 'Cadar'),
  ('cadar_xabag', 'en', 'Chewing Gum'),
  ('shibis', 'so', 'Shibis'),
  ('shibis', 'en', 'Crisps'),
  ('macsaro', 'so', 'Macsaro'),
  ('macsaro', 'en', 'Popcorn'),
  ('kornfaleeks_375g', 'so', 'Kornfaleeks 375g'),
  ('kornfaleeks_375g', 'en', 'Cornflakes 375g'),
  ('halwa_kg', 'so', 'Halwa 1kg'),
  ('halwa_kg', 'en', 'Halwa 1kg'),
  ('malab_500g', 'so', 'Malab 500g'),
  ('malab_500g', 'en', 'Honey 500g'),
  ('subag_kg', 'so', 'Subag 1kg'),
  ('subag_kg', 'en', 'Ghee 1kg'),
  ('jam_400g', 'so', 'Jam 400g'),
  ('jam_400g', 'en', 'Jam 400g'),
  ('xawaash_100g', 'so', 'Xawaash 100g'),
  ('xawaash_100g', 'en', 'Mixed Spice 100g'),
  ('basbaas_budo_100g', 'so', 'Basbaas Budo 100g'),
  ('basbaas_budo_100g', 'en', 'Chilli Powder 100g'),
  ('filfil_100g', 'so', 'Filfil Madow 100g'),
  ('filfil_100g', 'en', 'Black Pepper 100g'),
  ('kamuun_100g', 'so', 'Kamuun 100g'),
  ('kamuun_100g', 'en', 'Cumin 100g'),
  ('hayl_50g', 'so', 'Hayl 50g'),
  ('hayl_50g', 'en', 'Cardamom 50g'),
  ('qorfe_50g', 'so', 'Qorfe 50g'),
  ('qorfe_50g', 'en', 'Cinnamon 50g'),
  ('huruud_100g', 'so', 'Huruud 100g'),
  ('huruud_100g', 'en', 'Turmeric 100g'),
  ('maraq_cube', 'so', 'Maraq Cube'),
  ('maraq_cube', 'en', 'Stock Cubes'),
  ('khal_500ml', 'so', 'Khal 500ml'),
  ('khal_500ml', 'en', 'Vinegar 500ml'),
  ('tamaate_paste_400g', 'so', 'Tamaate Paste 400g'),
  ('tamaate_paste_400g', 'en', 'Tomato Paste 400g'),
  ('tamaate_paste_70g', 'so', 'Tamaate Paste 70g'),
  ('tamaate_paste_70g', 'en', 'Tomato Paste 70g'),
  ('tuun_qasacad', 'so', 'Tuun Qasacad'),
  ('tuun_qasacad', 'en', 'Canned Tuna'),
  ('sardiin_qasacad', 'so', 'Sardiin Qasacad'),
  ('sardiin_qasacad', 'en', 'Canned Sardines'),
  ('digir_qasacad', 'so', 'Digir Qasacad'),
  ('digir_qasacad', 'en', 'Canned Beans'),
  ('tamaate_qasacad', 'so', 'Tamaate Qasacad'),
  ('tamaate_qasacad', 'en', 'Canned Tomatoes'),
  ('caano_qasacad', 'so', 'Caano Qasacad'),
  ('caano_qasacad', 'en', 'Evaporated Milk'),
  ('saabuun_dharka', 'so', 'Saabuun Dharka'),
  ('saabuun_dharka', 'en', 'Laundry Soap Bar'),
  ('daacuun_1kg', 'so', 'Daacuun 1kg'),
  ('daacuun_1kg', 'en', 'Detergent Powder 1kg'),
  ('saabuun_gacmeed', 'so', 'Saabuun Gacmeed'),
  ('saabuun_gacmeed', 'en', 'Hand Soap'),
  ('shaambo_400ml', 'so', 'Shaambo 400ml'),
  ('shaambo_400ml', 'en', 'Shampoo 400ml'),
  ('cadayga', 'so', 'Cadayga'),
  ('cadayga', 'en', 'Toothpaste'),
  ('caleen_suuf', 'so', 'Caleen Suuf'),
  ('caleen_suuf', 'en', 'Tissue Roll'),
  ('kabriid', 'so', 'Kabriid'),
  ('kabriid', 'en', 'Matches'),
  ('shamac', 'so', 'Shamac'),
  ('shamac', 'en', 'Candle'),
  ('bataari_aa', 'so', 'Bataari AA'),
  ('bataari_aa', 'en', 'Batteries AA'),
  ('baaldi', 'so', 'Baaldi'),
  ('baaldi', 'en', 'Bucket'),
  ('xaaqin', 'so', 'Xaaqin'),
  ('xaaqin', 'en', 'Broom'),
  ('foyl', 'so', 'Foyl'),
  ('foyl', 'en', 'Aluminium Foil'),
  ('dabqaad', 'so', 'Dab-qaad'),
  ('dabqaad', 'en', 'Lighter'),
  ('caafimaad_panadol', 'so', 'Panadol'),
  ('caafimaad_panadol', 'en', 'Paracetamol'),
  ('caafimaad_plaster', 'so', 'Plaaster'),
  ('caafimaad_plaster', 'en', 'Plasters'),
  ('caafimaad_cotton', 'so', 'Suuf Caafimaad'),
  ('caafimaad_cotton', 'en', 'Cotton Wool')
) as a(item_code, lang, alias_text) on a.item_code = i.code
on conflict (item_id, language_code, alias_text_norm) do nothing;

-- Search nicknames (is_display=false), stored under both languages so
-- type-ahead matches regardless of UI language.
insert into public.item_alias (item_id, alias_text, language_code, is_display, source, weight)
select i.id, a.alias_text, a.lang, false, 'platform', 0
from public.item i
join (values
  ('bariis_basmati_25kg', 'so', 'bariis'),
  ('bariis_basmati_25kg', 'en', 'bariis'),
  ('bariis_basmati_25kg', 'so', 'basmati'),
  ('bariis_basmati_25kg', 'en', 'basmati'),
  ('bariis_basmati_25kg', 'so', 'rice'),
  ('bariis_basmati_25kg', 'en', 'rice'),
  ('bariis_cad_25kg', 'so', 'bariis cad'),
  ('bariis_cad_25kg', 'en', 'bariis cad'),
  ('bariis_cad_25kg', 'so', 'white rice'),
  ('bariis_cad_25kg', 'en', 'white rice'),
  ('bariis_kg', 'so', 'bariis'),
  ('bariis_kg', 'en', 'bariis'),
  ('bariis_kg', 'so', 'rice'),
  ('bariis_kg', 'en', 'rice'),
  ('sonkor_50kg', 'so', 'sonkor'),
  ('sonkor_50kg', 'en', 'sonkor'),
  ('sonkor_50kg', 'so', 'sugar'),
  ('sonkor_50kg', 'en', 'sugar'),
  ('sonkor_kg', 'so', 'sonkor'),
  ('sonkor_kg', 'en', 'sonkor'),
  ('sonkor_kg', 'so', 'sugar'),
  ('sonkor_kg', 'en', 'sugar'),
  ('daqiiq_50kg', 'so', 'daqiiq'),
  ('daqiiq_50kg', 'en', 'daqiiq'),
  ('daqiiq_50kg', 'so', 'bur'),
  ('daqiiq_50kg', 'en', 'bur'),
  ('daqiiq_50kg', 'so', 'flour'),
  ('daqiiq_50kg', 'en', 'flour'),
  ('daqiiq_kg', 'so', 'daqiiq'),
  ('daqiiq_kg', 'en', 'daqiiq'),
  ('daqiiq_kg', 'so', 'flour'),
  ('daqiiq_kg', 'en', 'flour'),
  ('bur_caws_kg', 'so', 'bur caws'),
  ('bur_caws_kg', 'en', 'bur caws'),
  ('bur_caws_kg', 'so', 'semolina'),
  ('bur_caws_kg', 'en', 'semolina'),
  ('saliid_20l', 'so', 'saliid'),
  ('saliid_20l', 'en', 'saliid'),
  ('saliid_20l', 'so', 'oil'),
  ('saliid_20l', 'en', 'oil'),
  ('saliid_20l', 'so', 'saliid cunto'),
  ('saliid_20l', 'en', 'saliid cunto'),
  ('saliid_5l', 'so', 'saliid'),
  ('saliid_5l', 'en', 'saliid'),
  ('saliid_5l', 'so', 'oil'),
  ('saliid_5l', 'en', 'oil'),
  ('saliid_1l', 'so', 'saliid'),
  ('saliid_1l', 'en', 'saliid'),
  ('saliid_1l', 'so', 'oil'),
  ('saliid_1l', 'en', 'oil'),
  ('baasto_500g', 'so', 'baasto'),
  ('baasto_500g', 'en', 'baasto'),
  ('baasto_500g', 'so', 'pasta'),
  ('baasto_500g', 'en', 'pasta'),
  ('spageti_500g', 'so', 'spageti'),
  ('spageti_500g', 'en', 'spageti'),
  ('spageti_500g', 'so', 'baasto'),
  ('spageti_500g', 'en', 'baasto'),
  ('spageti_500g', 'so', 'spaghetti'),
  ('spageti_500g', 'en', 'spaghetti'),
  ('macrooni_400g', 'so', 'macrooni'),
  ('macrooni_400g', 'en', 'macrooni'),
  ('macrooni_400g', 'so', 'macaroni'),
  ('macrooni_400g', 'en', 'macaroni'),
  ('digir_kg', 'so', 'digir'),
  ('digir_kg', 'en', 'digir'),
  ('digir_kg', 'so', 'beans'),
  ('digir_kg', 'en', 'beans'),
  ('misir_kg', 'so', 'misir'),
  ('misir_kg', 'en', 'misir'),
  ('misir_kg', 'so', 'lentils'),
  ('misir_kg', 'en', 'lentils'),
  ('loobiya_kg', 'so', 'loobiya'),
  ('loobiya_kg', 'en', 'loobiya'),
  ('loobiya_kg', 'so', 'cowpeas'),
  ('loobiya_kg', 'en', 'cowpeas'),
  ('galley_kg', 'so', 'galley'),
  ('galley_kg', 'en', 'galley'),
  ('galley_kg', 'so', 'maize'),
  ('galley_kg', 'en', 'maize'),
  ('galley_kg', 'so', 'corn'),
  ('galley_kg', 'en', 'corn'),
  ('cusbo_kg', 'so', 'cusbo'),
  ('cusbo_kg', 'en', 'cusbo'),
  ('cusbo_kg', 'so', 'salt'),
  ('cusbo_kg', 'en', 'salt'),
  ('timir_500g', 'so', 'timir'),
  ('timir_500g', 'en', 'timir'),
  ('timir_500g', 'so', 'dates'),
  ('timir_500g', 'en', 'dates'),
  ('shaah_caleen_250g', 'so', 'shaah'),
  ('shaah_caleen_250g', 'en', 'shaah'),
  ('shaah_caleen_250g', 'so', 'tea'),
  ('shaah_caleen_250g', 'en', 'tea'),
  ('shaah_caleen_250g', 'so', 'caleen'),
  ('shaah_caleen_250g', 'en', 'caleen'),
  ('shaah_caleen_500g', 'so', 'shaah'),
  ('shaah_caleen_500g', 'en', 'shaah'),
  ('shaah_caleen_500g', 'so', 'tea'),
  ('shaah_caleen_500g', 'en', 'tea'),
  ('bun_250g', 'so', 'bun'),
  ('bun_250g', 'en', 'bun'),
  ('bun_250g', 'so', 'coffee'),
  ('bun_250g', 'en', 'coffee'),
  ('caano_budo_400g', 'so', 'caano'),
  ('caano_budo_400g', 'en', 'caano'),
  ('caano_budo_400g', 'so', 'milk'),
  ('caano_budo_400g', 'en', 'milk'),
  ('caano_budo_400g', 'so', 'caano budo'),
  ('caano_budo_400g', 'en', 'caano budo'),
  ('caano_budo_2500g', 'so', 'caano'),
  ('caano_budo_2500g', 'en', 'caano'),
  ('caano_budo_2500g', 'so', 'milk powder'),
  ('caano_budo_2500g', 'en', 'milk powder'),
  ('caano_fariid_1l', 'so', 'caano'),
  ('caano_fariid_1l', 'en', 'caano'),
  ('caano_fariid_1l', 'so', 'milk'),
  ('caano_fariid_1l', 'en', 'milk'),
  ('biyo_500ml', 'so', 'biyo'),
  ('biyo_500ml', 'en', 'biyo'),
  ('biyo_500ml', 'so', 'water'),
  ('biyo_500ml', 'en', 'water'),
  ('biyo_1500ml', 'so', 'biyo'),
  ('biyo_1500ml', 'en', 'biyo'),
  ('biyo_1500ml', 'so', 'water'),
  ('biyo_1500ml', 'en', 'water'),
  ('biyo_carton', 'so', 'biyo carton'),
  ('biyo_carton', 'en', 'biyo carton'),
  ('biyo_carton', 'so', 'water carton'),
  ('biyo_carton', 'en', 'water carton'),
  ('soda_300ml', 'so', 'cabitaan'),
  ('soda_300ml', 'en', 'cabitaan'),
  ('soda_300ml', 'so', 'soda'),
  ('soda_300ml', 'en', 'soda'),
  ('soda_300ml', 'so', 'coca'),
  ('soda_300ml', 'en', 'coca'),
  ('soda_1500ml', 'so', 'cabitaan'),
  ('soda_1500ml', 'en', 'cabitaan'),
  ('soda_1500ml', 'so', 'soda'),
  ('soda_1500ml', 'en', 'soda'),
  ('casiir_1l', 'so', 'casiir'),
  ('casiir_1l', 'en', 'casiir'),
  ('casiir_1l', 'so', 'juice'),
  ('casiir_1l', 'en', 'juice'),
  ('vimto_1l', 'so', 'vimto'),
  ('vimto_1l', 'en', 'vimto'),
  ('vimto_1l', 'so', 'sharaab'),
  ('vimto_1l', 'en', 'sharaab'),
  ('tamar_hindi_1l', 'so', 'tamar hindi'),
  ('tamar_hindi_1l', 'en', 'tamar hindi'),
  ('tamar_hindi_1l', 'so', 'tamarind'),
  ('tamar_hindi_1l', 'en', 'tamarind'),
  ('biskut_packet', 'so', 'biskut'),
  ('biskut_packet', 'en', 'biskut'),
  ('biskut_packet', 'so', 'biscuit'),
  ('biskut_packet', 'en', 'biscuit'),
  ('biskut_packet', 'so', 'cabis'),
  ('biskut_packet', 'en', 'cabis'),
  ('shukulaato', 'so', 'shukulaato'),
  ('shukulaato', 'en', 'shukulaato'),
  ('shukulaato', 'so', 'chocolate'),
  ('shukulaato', 'en', 'chocolate'),
  ('nacnac', 'so', 'nacnac'),
  ('nacnac', 'en', 'nacnac'),
  ('nacnac', 'so', 'sweets'),
  ('nacnac', 'en', 'sweets'),
  ('nacnac', 'so', 'candy'),
  ('nacnac', 'en', 'candy'),
  ('cadar_xabag', 'so', 'cadar'),
  ('cadar_xabag', 'en', 'cadar'),
  ('cadar_xabag', 'so', 'gum'),
  ('cadar_xabag', 'en', 'gum'),
  ('shibis', 'so', 'shibis'),
  ('shibis', 'en', 'shibis'),
  ('shibis', 'so', 'crisps'),
  ('shibis', 'en', 'crisps'),
  ('shibis', 'so', 'chips'),
  ('shibis', 'en', 'chips'),
  ('macsaro', 'so', 'macsaro'),
  ('macsaro', 'en', 'macsaro'),
  ('macsaro', 'so', 'popcorn'),
  ('macsaro', 'en', 'popcorn'),
  ('kornfaleeks_375g', 'so', 'kornfaleeks'),
  ('kornfaleeks_375g', 'en', 'kornfaleeks'),
  ('kornfaleeks_375g', 'so', 'cornflakes'),
  ('kornfaleeks_375g', 'en', 'cornflakes'),
  ('halwa_kg', 'so', 'halwa'),
  ('halwa_kg', 'en', 'halwa'),
  ('malab_500g', 'so', 'malab'),
  ('malab_500g', 'en', 'malab'),
  ('malab_500g', 'so', 'honey'),
  ('malab_500g', 'en', 'honey'),
  ('subag_kg', 'so', 'subag'),
  ('subag_kg', 'en', 'subag'),
  ('subag_kg', 'so', 'ghee'),
  ('subag_kg', 'en', 'ghee'),
  ('jam_400g', 'so', 'jam'),
  ('jam_400g', 'en', 'jam'),
  ('xawaash_100g', 'so', 'xawaash'),
  ('xawaash_100g', 'en', 'xawaash'),
  ('xawaash_100g', 'so', 'spice'),
  ('xawaash_100g', 'en', 'spice'),
  ('basbaas_budo_100g', 'so', 'basbaas'),
  ('basbaas_budo_100g', 'en', 'basbaas'),
  ('basbaas_budo_100g', 'so', 'chilli'),
  ('basbaas_budo_100g', 'en', 'chilli'),
  ('basbaas_budo_100g', 'so', 'chili'),
  ('basbaas_budo_100g', 'en', 'chili'),
  ('filfil_100g', 'so', 'filfil'),
  ('filfil_100g', 'en', 'filfil'),
  ('filfil_100g', 'so', 'pepper'),
  ('filfil_100g', 'en', 'pepper'),
  ('kamuun_100g', 'so', 'kamuun'),
  ('kamuun_100g', 'en', 'kamuun'),
  ('kamuun_100g', 'so', 'cumin'),
  ('kamuun_100g', 'en', 'cumin'),
  ('hayl_50g', 'so', 'hayl'),
  ('hayl_50g', 'en', 'hayl'),
  ('hayl_50g', 'so', 'cardamom'),
  ('hayl_50g', 'en', 'cardamom'),
  ('qorfe_50g', 'so', 'qorfe'),
  ('qorfe_50g', 'en', 'qorfe'),
  ('qorfe_50g', 'so', 'cinnamon'),
  ('qorfe_50g', 'en', 'cinnamon'),
  ('huruud_100g', 'so', 'huruud'),
  ('huruud_100g', 'en', 'huruud'),
  ('huruud_100g', 'so', 'turmeric'),
  ('huruud_100g', 'en', 'turmeric'),
  ('maraq_cube', 'so', 'maraq'),
  ('maraq_cube', 'en', 'maraq'),
  ('maraq_cube', 'so', 'cube'),
  ('maraq_cube', 'en', 'cube'),
  ('maraq_cube', 'so', 'maggi'),
  ('maraq_cube', 'en', 'maggi'),
  ('khal_500ml', 'so', 'khal'),
  ('khal_500ml', 'en', 'khal'),
  ('khal_500ml', 'so', 'vinegar'),
  ('khal_500ml', 'en', 'vinegar'),
  ('tamaate_paste_400g', 'so', 'tamaate'),
  ('tamaate_paste_400g', 'en', 'tamaate'),
  ('tamaate_paste_400g', 'so', 'tomato paste'),
  ('tamaate_paste_400g', 'en', 'tomato paste'),
  ('tamaate_paste_70g', 'so', 'tamaate'),
  ('tamaate_paste_70g', 'en', 'tamaate'),
  ('tamaate_paste_70g', 'so', 'tomato'),
  ('tamaate_paste_70g', 'en', 'tomato'),
  ('tuun_qasacad', 'so', 'tuun'),
  ('tuun_qasacad', 'en', 'tuun'),
  ('tuun_qasacad', 'so', 'tuna'),
  ('tuun_qasacad', 'en', 'tuna'),
  ('sardiin_qasacad', 'so', 'sardiin'),
  ('sardiin_qasacad', 'en', 'sardiin'),
  ('sardiin_qasacad', 'so', 'sardine'),
  ('sardiin_qasacad', 'en', 'sardine'),
  ('digir_qasacad', 'so', 'digir'),
  ('digir_qasacad', 'en', 'digir'),
  ('digir_qasacad', 'so', 'beans'),
  ('digir_qasacad', 'en', 'beans'),
  ('tamaate_qasacad', 'so', 'tamaate'),
  ('tamaate_qasacad', 'en', 'tamaate'),
  ('tamaate_qasacad', 'so', 'tomatoes'),
  ('tamaate_qasacad', 'en', 'tomatoes'),
  ('caano_qasacad', 'so', 'caano'),
  ('caano_qasacad', 'en', 'caano'),
  ('caano_qasacad', 'so', 'evaporated milk'),
  ('caano_qasacad', 'en', 'evaporated milk'),
  ('saabuun_dharka', 'so', 'saabuun'),
  ('saabuun_dharka', 'en', 'saabuun'),
  ('saabuun_dharka', 'so', 'soap'),
  ('saabuun_dharka', 'en', 'soap'),
  ('daacuun_1kg', 'so', 'daacuun'),
  ('daacuun_1kg', 'en', 'daacuun'),
  ('daacuun_1kg', 'so', 'omo'),
  ('daacuun_1kg', 'en', 'omo'),
  ('daacuun_1kg', 'so', 'detergent'),
  ('daacuun_1kg', 'en', 'detergent'),
  ('saabuun_gacmeed', 'so', 'saabuun'),
  ('saabuun_gacmeed', 'en', 'saabuun'),
  ('saabuun_gacmeed', 'so', 'soap'),
  ('saabuun_gacmeed', 'en', 'soap'),
  ('shaambo_400ml', 'so', 'shaambo'),
  ('shaambo_400ml', 'en', 'shaambo'),
  ('shaambo_400ml', 'so', 'shampoo'),
  ('shaambo_400ml', 'en', 'shampoo'),
  ('cadayga', 'so', 'cadayga'),
  ('cadayga', 'en', 'cadayga'),
  ('cadayga', 'so', 'toothpaste'),
  ('cadayga', 'en', 'toothpaste'),
  ('cadayga', 'so', 'colgate'),
  ('cadayga', 'en', 'colgate'),
  ('caleen_suuf', 'so', 'suuf'),
  ('caleen_suuf', 'en', 'suuf'),
  ('caleen_suuf', 'so', 'tissue'),
  ('caleen_suuf', 'en', 'tissue'),
  ('kabriid', 'so', 'kabriid'),
  ('kabriid', 'en', 'kabriid'),
  ('kabriid', 'so', 'matches'),
  ('kabriid', 'en', 'matches'),
  ('shamac', 'so', 'shamac'),
  ('shamac', 'en', 'shamac'),
  ('shamac', 'so', 'candle'),
  ('shamac', 'en', 'candle'),
  ('bataari_aa', 'so', 'bataari'),
  ('bataari_aa', 'en', 'bataari'),
  ('bataari_aa', 'so', 'battery'),
  ('bataari_aa', 'en', 'battery'),
  ('baaldi', 'so', 'baaldi'),
  ('baaldi', 'en', 'baaldi'),
  ('baaldi', 'so', 'bucket'),
  ('baaldi', 'en', 'bucket'),
  ('xaaqin', 'so', 'xaaqin'),
  ('xaaqin', 'en', 'xaaqin'),
  ('xaaqin', 'so', 'broom'),
  ('xaaqin', 'en', 'broom'),
  ('foyl', 'so', 'foyl'),
  ('foyl', 'en', 'foyl'),
  ('foyl', 'so', 'foil'),
  ('foyl', 'en', 'foil'),
  ('dabqaad', 'so', 'dabqaad'),
  ('dabqaad', 'en', 'dabqaad'),
  ('dabqaad', 'so', 'lighter'),
  ('dabqaad', 'en', 'lighter'),
  ('caafimaad_panadol', 'so', 'panadol'),
  ('caafimaad_panadol', 'en', 'panadol'),
  ('caafimaad_panadol', 'so', 'paracetamol'),
  ('caafimaad_panadol', 'en', 'paracetamol'),
  ('caafimaad_plaster', 'so', 'plaaster'),
  ('caafimaad_plaster', 'en', 'plaaster'),
  ('caafimaad_plaster', 'so', 'plaster'),
  ('caafimaad_plaster', 'en', 'plaster'),
  ('caafimaad_cotton', 'so', 'suuf'),
  ('caafimaad_cotton', 'en', 'suuf'),
  ('caafimaad_cotton', 'so', 'cotton'),
  ('caafimaad_cotton', 'en', 'cotton')
) as a(item_code, lang, alias_text) on a.item_code = i.code
on conflict (item_id, language_code, alias_text_norm) do nothing;

--------------------------------------------------------------------
-- 5. Item units — single base packaging per SKU (conversion=1,
--    default for both sale and receive).
--------------------------------------------------------------------
insert into public.item_unit (item_id, unit_code, conversion_to_base,
  is_default_sale, is_default_receive, sort_order, is_active)
select i.id, u.unit_code, 1, true, true, 1, true
from public.item i
join (values
  ('bariis_basmati_25kg', 'bag'),
  ('bariis_cad_25kg', 'bag'),
  ('bariis_kg', 'kg'),
  ('sonkor_50kg', 'bag'),
  ('sonkor_kg', 'kg'),
  ('daqiiq_50kg', 'bag'),
  ('daqiiq_kg', 'kg'),
  ('bur_caws_kg', 'kg'),
  ('saliid_20l', 'jerrycan'),
  ('saliid_5l', 'jerrycan'),
  ('saliid_1l', 'bottle'),
  ('baasto_500g', 'packet'),
  ('spageti_500g', 'packet'),
  ('macrooni_400g', 'packet'),
  ('digir_kg', 'kg'),
  ('misir_kg', 'kg'),
  ('loobiya_kg', 'kg'),
  ('galley_kg', 'kg'),
  ('cusbo_kg', 'kg'),
  ('timir_500g', 'packet'),
  ('shaah_caleen_250g', 'packet'),
  ('shaah_caleen_500g', 'packet'),
  ('bun_250g', 'packet'),
  ('caano_budo_400g', 'tin'),
  ('caano_budo_2500g', 'tin'),
  ('caano_fariid_1l', 'bottle'),
  ('biyo_500ml', 'bottle'),
  ('biyo_1500ml', 'bottle'),
  ('biyo_carton', 'carton'),
  ('soda_300ml', 'bottle'),
  ('soda_1500ml', 'bottle'),
  ('casiir_1l', 'bottle'),
  ('vimto_1l', 'bottle'),
  ('tamar_hindi_1l', 'bottle'),
  ('biskut_packet', 'packet'),
  ('shukulaato', 'piece'),
  ('nacnac', 'packet'),
  ('cadar_xabag', 'packet'),
  ('shibis', 'packet'),
  ('macsaro', 'packet'),
  ('kornfaleeks_375g', 'box'),
  ('halwa_kg', 'piece'),
  ('malab_500g', 'jar'),
  ('subag_kg', 'tin'),
  ('jam_400g', 'jar'),
  ('xawaash_100g', 'packet'),
  ('basbaas_budo_100g', 'packet'),
  ('filfil_100g', 'packet'),
  ('kamuun_100g', 'packet'),
  ('hayl_50g', 'packet'),
  ('qorfe_50g', 'packet'),
  ('huruud_100g', 'packet'),
  ('maraq_cube', 'box'),
  ('khal_500ml', 'bottle'),
  ('tamaate_paste_400g', 'can'),
  ('tamaate_paste_70g', 'can'),
  ('tuun_qasacad', 'can'),
  ('sardiin_qasacad', 'can'),
  ('digir_qasacad', 'can'),
  ('tamaate_qasacad', 'can'),
  ('caano_qasacad', 'can'),
  ('saabuun_dharka', 'piece'),
  ('daacuun_1kg', 'packet'),
  ('saabuun_gacmeed', 'piece'),
  ('shaambo_400ml', 'bottle'),
  ('cadayga', 'piece'),
  ('caleen_suuf', 'piece'),
  ('kabriid', 'packet'),
  ('shamac', 'piece'),
  ('bataari_aa', 'packet'),
  ('baaldi', 'piece'),
  ('xaaqin', 'piece'),
  ('foyl', 'piece'),
  ('dabqaad', 'piece'),
  ('caafimaad_panadol', 'packet'),
  ('caafimaad_plaster', 'packet'),
  ('caafimaad_cotton', 'packet')
) as u(item_code, unit_code) on u.item_code = i.code
on conflict (item_id, unit_code, conversion_to_base) do nothing;

--------------------------------------------------------------------
-- 6. Templates (both siblings).
--------------------------------------------------------------------
insert into public.template (code, kind, name, locale_default, currency_default, version, is_active)
values
  ('test_dukaan_cunto',  'shop_starter', 'Test Dukaan Cunto',  'so', 'USD', 1, true),
  ('empty_dukaan_cunto', 'shop_starter', 'Empty Dukaan Cunto', 'so', 'USD', 1, true)
on conflict (code, version) do nothing;

-- ---- empty_dukaan_cunto ----
insert into public.template_pack (template_id, code, version, is_required, file_path)
select t.id, p.code, p.version, p.is_required, p.file_path
from public.template t
cross join (values
  ('settings', 1, true, 'templates/empty_dukaan_cunto/settings.json'),
  ('expense_categories', 1, true, 'templates/empty_dukaan_cunto/expense-categories.json')
) as p(code, version, is_required, file_path)
where t.code = 'empty_dukaan_cunto' and t.version = 1
on conflict (template_id, code, version) do nothing;

insert into public.template_setting (template_id, key, value)
select t.id, s.key, s.value
from public.template t
cross join (values
  ('locale_default', to_jsonb('so'::text)),
  ('currency_default', to_jsonb('USD'::text)),
  ('timezone_default', to_jsonb('Africa/Mogadishu'::text)),
  ('sale_payment_default', to_jsonb('cash'::text)),
  ('receive_payment_default', to_jsonb('credit'::text)),
  ('negative_stock_policy', to_jsonb('warn'::text))
) as s(key, value)
where t.code = 'empty_dukaan_cunto' and t.version = 1
on conflict (template_id, key) do nothing;

insert into public.template_unit (template_id, unit_code, label, sort_order)
select t.id, u.unit_code, u.label, u.sort_order
from public.template t
cross join (values
  ('bag', jsonb_build_object('en', 'Bag', 'so', 'Bac'), 1),
  ('bottle', jsonb_build_object('en', 'Bottle', 'so', 'Dhalo'), 2),
  ('box', jsonb_build_object('en', 'Box', 'so', 'Sanduuq'), 3),
  ('can', jsonb_build_object('en', 'Can', 'so', 'Qasacad'), 4),
  ('carton', jsonb_build_object('en', 'Carton', 'so', 'Kartoon'), 5),
  ('jar', jsonb_build_object('en', 'Jar', 'so', 'Jaar'), 6),
  ('jerrycan', jsonb_build_object('en', 'Jerrycan', 'so', 'Jerigan'), 7),
  ('kg', jsonb_build_object('en', 'Kg', 'so', 'Kiilo'), 8),
  ('packet', jsonb_build_object('en', 'Packet', 'so', 'Baakad'), 9),
  ('piece', jsonb_build_object('en', 'Piece', 'so', 'Xabba'), 10),
  ('tin', jsonb_build_object('en', 'Tin', 'so', 'Tini'), 11)
) as u(unit_code, label, sort_order)
where t.code = 'empty_dukaan_cunto' and t.version = 1
on conflict (template_id, unit_code) do nothing;

insert into public.template_expense_category (template_id, code, name, name_translations, sort_order)
select t.id, c.code, c.name, c.translations, c.sort_order
from public.template t
cross join (values
  ('rent', 'Rent', jsonb_build_object('en', 'Rent', 'so', 'Kiro'), 1),
  ('electricity', 'Electricity', jsonb_build_object('en', 'Electricity', 'so', 'Koronto'), 2),
  ('water', 'Water', jsonb_build_object('en', 'Water', 'so', 'Biyo'), 3),
  ('salary', 'Salary', jsonb_build_object('en', 'Salary', 'so', 'Mushahar'), 4),
  ('transport', 'Transport', jsonb_build_object('en', 'Transport', 'so', 'Gaadiid'), 5),
  ('supplies', 'Supplies', jsonb_build_object('en', 'Supplies', 'so', 'Alaab'), 6),
  ('other', 'Other', jsonb_build_object('en', 'Other', 'so', 'Kale'), 7)
) as c(code, name, translations, sort_order)
where t.code = 'empty_dukaan_cunto' and t.version = 1
on conflict (template_id, code) do nothing;

-- ---- test_dukaan_cunto ----
insert into public.template_pack (template_id, code, version, is_required, file_path)
select t.id, p.code, p.version, p.is_required, p.file_path
from public.template t
cross join (values
  ('catalog', 1, true, 'templates/test_dukaan_cunto/catalog.json'),
  ('settings', 1, true, 'templates/test_dukaan_cunto/settings.json'),
  ('expense_categories', 1, true, 'templates/test_dukaan_cunto/expense-categories.json'),
  ('quick_actions', 1, false, 'templates/test_dukaan_cunto/quick-actions.json')
) as p(code, version, is_required, file_path)
where t.code = 'test_dukaan_cunto' and t.version = 1
on conflict (template_id, code, version) do nothing;

insert into public.template_setting (template_id, key, value)
select t.id, s.key, s.value
from public.template t
cross join (values
  ('locale_default', to_jsonb('so'::text)),
  ('currency_default', to_jsonb('USD'::text)),
  ('timezone_default', to_jsonb('Africa/Mogadishu'::text)),
  ('sale_payment_default', to_jsonb('cash'::text)),
  ('receive_payment_default', to_jsonb('credit'::text)),
  ('negative_stock_policy', to_jsonb('warn'::text))
) as s(key, value)
where t.code = 'test_dukaan_cunto' and t.version = 1
on conflict (template_id, key) do nothing;

insert into public.template_unit (template_id, unit_code, label, sort_order)
select t.id, u.unit_code, u.label, u.sort_order
from public.template t
cross join (values
  ('bag', jsonb_build_object('en', 'Bag', 'so', 'Bac'), 1),
  ('bottle', jsonb_build_object('en', 'Bottle', 'so', 'Dhalo'), 2),
  ('box', jsonb_build_object('en', 'Box', 'so', 'Sanduuq'), 3),
  ('can', jsonb_build_object('en', 'Can', 'so', 'Qasacad'), 4),
  ('carton', jsonb_build_object('en', 'Carton', 'so', 'Kartoon'), 5),
  ('jar', jsonb_build_object('en', 'Jar', 'so', 'Jaar'), 6),
  ('jerrycan', jsonb_build_object('en', 'Jerrycan', 'so', 'Jerigan'), 7),
  ('kg', jsonb_build_object('en', 'Kg', 'so', 'Kiilo'), 8),
  ('packet', jsonb_build_object('en', 'Packet', 'so', 'Baakad'), 9),
  ('piece', jsonb_build_object('en', 'Piece', 'so', 'Xabba'), 10),
  ('tin', jsonb_build_object('en', 'Tin', 'so', 'Tini'), 11)
) as u(unit_code, label, sort_order)
where t.code = 'test_dukaan_cunto' and t.version = 1
on conflict (template_id, unit_code) do nothing;

insert into public.template_expense_category (template_id, code, name, name_translations, sort_order)
select t.id, c.code, c.name, c.translations, c.sort_order
from public.template t
cross join (values
  ('rent', 'Rent', jsonb_build_object('en', 'Rent', 'so', 'Kiro'), 1),
  ('electricity', 'Electricity', jsonb_build_object('en', 'Electricity', 'so', 'Koronto'), 2),
  ('water', 'Water', jsonb_build_object('en', 'Water', 'so', 'Biyo'), 3),
  ('salary', 'Salary', jsonb_build_object('en', 'Salary', 'so', 'Mushahar'), 4),
  ('transport', 'Transport', jsonb_build_object('en', 'Transport', 'so', 'Gaadiid'), 5),
  ('supplies', 'Supplies', jsonb_build_object('en', 'Supplies', 'so', 'Alaab'), 6),
  ('other', 'Other', jsonb_build_object('en', 'Other', 'so', 'Kale'), 7)
) as c(code, name, translations, sort_order)
where t.code = 'test_dukaan_cunto' and t.version = 1
on conflict (template_id, code) do nothing;

--------------------------------------------------------------------
-- 7. Template items + item aliases + quick actions (TEST only).
--------------------------------------------------------------------
insert into public.template_item (template_id, item_code, item_id,
  suggested_sale_price, reorder_threshold, sort_order)
select t.id, i.code, i.id, p.price, p.reorder, p.sort_order
from public.template t
join (values
  ('bariis_basmati_25kg', 26.00::numeric, 2::numeric, 1),
  ('bariis_cad_25kg', 22.00::numeric, 2::numeric, 2),
  ('bariis_kg', 1.30::numeric, 10::numeric, 3),
  ('sonkor_50kg', 45.00::numeric, 1::numeric, 4),
  ('sonkor_kg', 1.40::numeric, 10::numeric, 5),
  ('daqiiq_50kg', 30.00::numeric, 1::numeric, 6),
  ('daqiiq_kg', 0.90::numeric, 10::numeric, 7),
  ('bur_caws_kg', 1.20::numeric, 6::numeric, 8),
  ('saliid_20l', 38.00::numeric, 1::numeric, 9),
  ('saliid_5l', 10.50::numeric, 3::numeric, 10),
  ('saliid_1l', 2.20::numeric, 8::numeric, 11),
  ('baasto_500g', 0.80::numeric, 15::numeric, 12),
  ('spageti_500g', 0.80::numeric, 15::numeric, 13),
  ('macrooni_400g', 0.75::numeric, 12::numeric, 14),
  ('digir_kg', 1.80::numeric, 8::numeric, 15),
  ('misir_kg', 1.60::numeric, 8::numeric, 16),
  ('loobiya_kg', 1.70::numeric, 6::numeric, 17),
  ('galley_kg', 0.70::numeric, 8::numeric, 18),
  ('cusbo_kg', 0.50::numeric, 10::numeric, 19),
  ('timir_500g', 2.00::numeric, 8::numeric, 20),
  ('shaah_caleen_250g', 1.50::numeric, 12::numeric, 21),
  ('shaah_caleen_500g', 2.80::numeric, 8::numeric, 22),
  ('bun_250g', 2.50::numeric, 6::numeric, 23),
  ('caano_budo_400g', 4.00::numeric, 8::numeric, 24),
  ('caano_budo_2500g', 18.00::numeric, 3::numeric, 25),
  ('caano_fariid_1l', 1.30::numeric, 10::numeric, 26),
  ('biyo_500ml', 0.30::numeric, 40::numeric, 27),
  ('biyo_1500ml', 0.60::numeric, 30::numeric, 28),
  ('biyo_carton', 6.50::numeric, 5::numeric, 29),
  ('soda_300ml', 0.50::numeric, 40::numeric, 30),
  ('soda_1500ml', 1.20::numeric, 15::numeric, 31),
  ('casiir_1l', 1.50::numeric, 10::numeric, 32),
  ('vimto_1l', 2.00::numeric, 8::numeric, 33),
  ('tamar_hindi_1l', 1.80::numeric, 6::numeric, 34),
  ('biskut_packet', 0.50::numeric, 20::numeric, 35),
  ('shukulaato', 0.60::numeric, 20::numeric, 36),
  ('nacnac', 0.40::numeric, 20::numeric, 37),
  ('cadar_xabag', 0.30::numeric, 20::numeric, 38),
  ('shibis', 0.50::numeric, 20::numeric, 39),
  ('macsaro', 0.50::numeric, 12::numeric, 40),
  ('kornfaleeks_375g', 3.00::numeric, 6::numeric, 41),
  ('halwa_kg', 4.50::numeric, 5::numeric, 42),
  ('malab_500g', 5.00::numeric, 5::numeric, 43),
  ('subag_kg', 7.00::numeric, 5::numeric, 44),
  ('jam_400g', 2.20::numeric, 6::numeric, 45),
  ('xawaash_100g', 1.00::numeric, 12::numeric, 46),
  ('basbaas_budo_100g', 0.90::numeric, 10::numeric, 47),
  ('filfil_100g', 1.20::numeric, 8::numeric, 48),
  ('kamuun_100g', 1.00::numeric, 8::numeric, 49),
  ('hayl_50g', 1.80::numeric, 6::numeric, 50),
  ('qorfe_50g', 1.00::numeric, 6::numeric, 51),
  ('huruud_100g', 0.90::numeric, 8::numeric, 52),
  ('maraq_cube', 1.50::numeric, 12::numeric, 53),
  ('khal_500ml', 1.00::numeric, 8::numeric, 54),
  ('tamaate_paste_400g', 1.20::numeric, 12::numeric, 55),
  ('tamaate_paste_70g', 0.40::numeric, 20::numeric, 56),
  ('tuun_qasacad', 1.50::numeric, 12::numeric, 57),
  ('sardiin_qasacad', 1.20::numeric, 12::numeric, 58),
  ('digir_qasacad', 1.00::numeric, 12::numeric, 59),
  ('tamaate_qasacad', 1.10::numeric, 10::numeric, 60),
  ('caano_qasacad', 1.30::numeric, 12::numeric, 61),
  ('saabuun_dharka', 0.60::numeric, 20::numeric, 62),
  ('daacuun_1kg', 2.00::numeric, 10::numeric, 63),
  ('saabuun_gacmeed', 0.50::numeric, 20::numeric, 64),
  ('shaambo_400ml', 2.50::numeric, 8::numeric, 65),
  ('cadayga', 1.00::numeric, 12::numeric, 66),
  ('caleen_suuf', 0.80::numeric, 15::numeric, 67),
  ('kabriid', 0.20::numeric, 30::numeric, 68),
  ('shamac', 0.30::numeric, 20::numeric, 69),
  ('bataari_aa', 0.80::numeric, 15::numeric, 70),
  ('baaldi', 2.50::numeric, 6::numeric, 71),
  ('xaaqin', 2.00::numeric, 6::numeric, 72),
  ('foyl', 1.50::numeric, 8::numeric, 73),
  ('dabqaad', 0.50::numeric, 20::numeric, 74),
  ('caafimaad_panadol', 0.50::numeric, 15::numeric, 75),
  ('caafimaad_plaster', 0.80::numeric, 12::numeric, 76),
  ('caafimaad_cotton', 0.70::numeric, 10::numeric, 77)
) as p(item_code, price, reorder, sort_order) on true
join public.item i on i.code = p.item_code
where t.code = 'test_dukaan_cunto' and t.version = 1
on conflict (template_id, item_code) do nothing;

insert into public.template_item_alias (template_id, item_code, language_code, alias_text, is_display, weight)
select t.id, a.item_code, a.lang, a.alias_text, true, 0
from public.template t
cross join (values
  ('bariis_basmati_25kg', 'so', 'Bariis Basmati 25kg'),
  ('bariis_basmati_25kg', 'en', 'Basmati Rice 25kg'),
  ('bariis_cad_25kg', 'so', 'Bariis Cad 25kg'),
  ('bariis_cad_25kg', 'en', 'White Rice 25kg'),
  ('bariis_kg', 'so', 'Bariis 1kg'),
  ('bariis_kg', 'en', 'Rice 1kg'),
  ('sonkor_50kg', 'so', 'Sonkor 50kg'),
  ('sonkor_50kg', 'en', 'Sugar 50kg'),
  ('sonkor_kg', 'so', 'Sonkor 1kg'),
  ('sonkor_kg', 'en', 'Sugar 1kg'),
  ('daqiiq_50kg', 'so', 'Daqiiq 50kg'),
  ('daqiiq_50kg', 'en', 'Wheat Flour 50kg'),
  ('daqiiq_kg', 'so', 'Daqiiq 1kg'),
  ('daqiiq_kg', 'en', 'Wheat Flour 1kg'),
  ('bur_caws_kg', 'so', 'Bur Caws 1kg'),
  ('bur_caws_kg', 'en', 'Semolina 1kg'),
  ('saliid_20l', 'so', 'Saliid Cunto 20L'),
  ('saliid_20l', 'en', 'Cooking Oil 20L'),
  ('saliid_5l', 'so', 'Saliid Cunto 5L'),
  ('saliid_5l', 'en', 'Cooking Oil 5L'),
  ('saliid_1l', 'so', 'Saliid Cunto 1L'),
  ('saliid_1l', 'en', 'Cooking Oil 1L'),
  ('baasto_500g', 'so', 'Baasto 500g'),
  ('baasto_500g', 'en', 'Pasta 500g'),
  ('spageti_500g', 'so', 'Spageti 500g'),
  ('spageti_500g', 'en', 'Spaghetti 500g'),
  ('macrooni_400g', 'so', 'Macrooni 400g'),
  ('macrooni_400g', 'en', 'Macaroni 400g'),
  ('digir_kg', 'so', 'Digir 1kg'),
  ('digir_kg', 'en', 'Beans 1kg'),
  ('misir_kg', 'so', 'Misir 1kg'),
  ('misir_kg', 'en', 'Lentils 1kg'),
  ('loobiya_kg', 'so', 'Loobiya 1kg'),
  ('loobiya_kg', 'en', 'Cowpeas 1kg'),
  ('galley_kg', 'so', 'Galley 1kg'),
  ('galley_kg', 'en', 'Maize 1kg'),
  ('cusbo_kg', 'so', 'Cusbo 1kg'),
  ('cusbo_kg', 'en', 'Salt 1kg'),
  ('timir_500g', 'so', 'Timir 500g'),
  ('timir_500g', 'en', 'Dates 500g'),
  ('shaah_caleen_250g', 'so', 'Shaah Caleen 250g'),
  ('shaah_caleen_250g', 'en', 'Tea Leaves 250g'),
  ('shaah_caleen_500g', 'so', 'Shaah Caleen 500g'),
  ('shaah_caleen_500g', 'en', 'Tea Leaves 500g'),
  ('bun_250g', 'so', 'Bun 250g'),
  ('bun_250g', 'en', 'Coffee 250g'),
  ('caano_budo_400g', 'so', 'Caano Budo 400g'),
  ('caano_budo_400g', 'en', 'Milk Powder 400g'),
  ('caano_budo_2500g', 'so', 'Caano Budo 2.5kg'),
  ('caano_budo_2500g', 'en', 'Milk Powder 2.5kg'),
  ('caano_fariid_1l', 'so', 'Caano Fariid 1L'),
  ('caano_fariid_1l', 'en', 'Fresh Milk 1L'),
  ('biyo_500ml', 'so', 'Biyo 500ml'),
  ('biyo_500ml', 'en', 'Water 500ml'),
  ('biyo_1500ml', 'so', 'Biyo 1.5L'),
  ('biyo_1500ml', 'en', 'Water 1.5L'),
  ('biyo_carton', 'so', 'Biyo Carton 12x1.5L'),
  ('biyo_carton', 'en', 'Water Carton 12x1.5L'),
  ('soda_300ml', 'so', 'Cabitaan 300ml'),
  ('soda_300ml', 'en', 'Soda 300ml'),
  ('soda_1500ml', 'so', 'Cabitaan 1.5L'),
  ('soda_1500ml', 'en', 'Soda 1.5L'),
  ('casiir_1l', 'so', 'Casiir 1L'),
  ('casiir_1l', 'en', 'Juice 1L'),
  ('vimto_1l', 'so', 'Vimto 1L'),
  ('vimto_1l', 'en', 'Vimto 1L'),
  ('tamar_hindi_1l', 'so', 'Tamar Hindi 1L'),
  ('tamar_hindi_1l', 'en', 'Tamarind Drink 1L'),
  ('biskut_packet', 'so', 'Biskut'),
  ('biskut_packet', 'en', 'Biscuits'),
  ('shukulaato', 'so', 'Shukulaato'),
  ('shukulaato', 'en', 'Chocolate'),
  ('nacnac', 'so', 'Nacnac'),
  ('nacnac', 'en', 'Sweets'),
  ('cadar_xabag', 'so', 'Cadar'),
  ('cadar_xabag', 'en', 'Chewing Gum'),
  ('shibis', 'so', 'Shibis'),
  ('shibis', 'en', 'Crisps'),
  ('macsaro', 'so', 'Macsaro'),
  ('macsaro', 'en', 'Popcorn'),
  ('kornfaleeks_375g', 'so', 'Kornfaleeks 375g'),
  ('kornfaleeks_375g', 'en', 'Cornflakes 375g'),
  ('halwa_kg', 'so', 'Halwa 1kg'),
  ('halwa_kg', 'en', 'Halwa 1kg'),
  ('malab_500g', 'so', 'Malab 500g'),
  ('malab_500g', 'en', 'Honey 500g'),
  ('subag_kg', 'so', 'Subag 1kg'),
  ('subag_kg', 'en', 'Ghee 1kg'),
  ('jam_400g', 'so', 'Jam 400g'),
  ('jam_400g', 'en', 'Jam 400g'),
  ('xawaash_100g', 'so', 'Xawaash 100g'),
  ('xawaash_100g', 'en', 'Mixed Spice 100g'),
  ('basbaas_budo_100g', 'so', 'Basbaas Budo 100g'),
  ('basbaas_budo_100g', 'en', 'Chilli Powder 100g'),
  ('filfil_100g', 'so', 'Filfil Madow 100g'),
  ('filfil_100g', 'en', 'Black Pepper 100g'),
  ('kamuun_100g', 'so', 'Kamuun 100g'),
  ('kamuun_100g', 'en', 'Cumin 100g'),
  ('hayl_50g', 'so', 'Hayl 50g'),
  ('hayl_50g', 'en', 'Cardamom 50g'),
  ('qorfe_50g', 'so', 'Qorfe 50g'),
  ('qorfe_50g', 'en', 'Cinnamon 50g'),
  ('huruud_100g', 'so', 'Huruud 100g'),
  ('huruud_100g', 'en', 'Turmeric 100g'),
  ('maraq_cube', 'so', 'Maraq Cube'),
  ('maraq_cube', 'en', 'Stock Cubes'),
  ('khal_500ml', 'so', 'Khal 500ml'),
  ('khal_500ml', 'en', 'Vinegar 500ml'),
  ('tamaate_paste_400g', 'so', 'Tamaate Paste 400g'),
  ('tamaate_paste_400g', 'en', 'Tomato Paste 400g'),
  ('tamaate_paste_70g', 'so', 'Tamaate Paste 70g'),
  ('tamaate_paste_70g', 'en', 'Tomato Paste 70g'),
  ('tuun_qasacad', 'so', 'Tuun Qasacad'),
  ('tuun_qasacad', 'en', 'Canned Tuna'),
  ('sardiin_qasacad', 'so', 'Sardiin Qasacad'),
  ('sardiin_qasacad', 'en', 'Canned Sardines'),
  ('digir_qasacad', 'so', 'Digir Qasacad'),
  ('digir_qasacad', 'en', 'Canned Beans'),
  ('tamaate_qasacad', 'so', 'Tamaate Qasacad'),
  ('tamaate_qasacad', 'en', 'Canned Tomatoes'),
  ('caano_qasacad', 'so', 'Caano Qasacad'),
  ('caano_qasacad', 'en', 'Evaporated Milk'),
  ('saabuun_dharka', 'so', 'Saabuun Dharka'),
  ('saabuun_dharka', 'en', 'Laundry Soap Bar'),
  ('daacuun_1kg', 'so', 'Daacuun 1kg'),
  ('daacuun_1kg', 'en', 'Detergent Powder 1kg'),
  ('saabuun_gacmeed', 'so', 'Saabuun Gacmeed'),
  ('saabuun_gacmeed', 'en', 'Hand Soap'),
  ('shaambo_400ml', 'so', 'Shaambo 400ml'),
  ('shaambo_400ml', 'en', 'Shampoo 400ml'),
  ('cadayga', 'so', 'Cadayga'),
  ('cadayga', 'en', 'Toothpaste'),
  ('caleen_suuf', 'so', 'Caleen Suuf'),
  ('caleen_suuf', 'en', 'Tissue Roll'),
  ('kabriid', 'so', 'Kabriid'),
  ('kabriid', 'en', 'Matches'),
  ('shamac', 'so', 'Shamac'),
  ('shamac', 'en', 'Candle'),
  ('bataari_aa', 'so', 'Bataari AA'),
  ('bataari_aa', 'en', 'Batteries AA'),
  ('baaldi', 'so', 'Baaldi'),
  ('baaldi', 'en', 'Bucket'),
  ('xaaqin', 'so', 'Xaaqin'),
  ('xaaqin', 'en', 'Broom'),
  ('foyl', 'so', 'Foyl'),
  ('foyl', 'en', 'Aluminium Foil'),
  ('dabqaad', 'so', 'Dab-qaad'),
  ('dabqaad', 'en', 'Lighter'),
  ('caafimaad_panadol', 'so', 'Panadol'),
  ('caafimaad_panadol', 'en', 'Paracetamol'),
  ('caafimaad_plaster', 'so', 'Plaaster'),
  ('caafimaad_plaster', 'en', 'Plasters'),
  ('caafimaad_cotton', 'so', 'Suuf Caafimaad'),
  ('caafimaad_cotton', 'en', 'Cotton Wool')
) as a(item_code, lang, alias_text)
where t.code = 'test_dukaan_cunto' and t.version = 1
on conflict (template_id, item_code, language_code, alias_text_norm) do nothing;

insert into public.template_quick_action (template_id, screen, position, item_code, label)
select t.id, q.screen, q.position, q.item_code, null
from public.template t
cross join (values
  ('sale', 1, 'bariis_basmati_25kg'),
  ('sale', 2, 'sonkor_kg'),
  ('sale', 3, 'saliid_1l'),
  ('sale', 4, 'baasto_500g'),
  ('sale', 5, 'shaah_caleen_250g'),
  ('sale', 6, 'biyo_500ml'),
  ('receive', 1, 'bariis_basmati_25kg'),
  ('receive', 2, 'sonkor_kg'),
  ('receive', 3, 'saliid_1l'),
  ('receive', 4, 'shaah_caleen_250g')
) as q(screen, position, item_code)
where t.code = 'test_dukaan_cunto' and t.version = 1
on conflict (template_id, screen, position) do nothing;
