-- 0017 — lazy apply_template variant: merged into 0011 + 0012.
--
-- Pre-v2, this file redefined apply_template to skip the eager
-- per-item materialization done by 0012 and instead pre-activate only
-- template_quick_action favorites, leaning on a separate
-- activate_catalog_item RPC for first-touch flows.
--
-- v2 collapses that split:
--   - ensure_shop_item (0011) is the lazy activator. It's already
--     idempotent and does the right thing whether called from
--     apply_template, the cashier's tap-on-an-unactivated-item path,
--     or any future surface.
--   - apply_template (0012) walks every template_item and routes each
--     row through ensure_shop_item / create_shop_item. There's no
--     separate "favorites-only" variant any more — a template that
--     wants minimal materialization simply omits the rows it doesn't
--     want pre-activated from template_item.
--
-- This migration is therefore a no-op; kept as a numbered file so the
-- migration sequence stays load-bearing and downstream files don't
-- need to be renumbered.
select 1;
